### ISSUE TITLE
Error when using google cloud storage as a backend

### ISSUE THREAD

**Issue by sharabhshukla** [bytehub-ai/bytehub#9]
Hi, I am trying to get my setup working on google cloud, when i try saving the dataframe to cloud storage, using fs.save_datframe I run into an error like the one shown below,

_call non-retriable exception: Disallowed unicode characters present in object name ''tutorial/feature/append-dataframe/partition=npartitions=1

 I confirmed my google cloud storage saving functionality for writing dataframe using . to_parquest and supplying the google cloud storage path gs://{bucketname}/{foldername}, which seems to work as expected.

**Comment by sharabhshukla** [comment]
Also, if i get this to work, I could also contribute my notebook as an example for setting up bytehub fs on gcp.

**Comment by sharabhshukla** [comment]
That error is mostly likely comming from gcsfs, a library needed for communicating with gcs, which I needed to install separately. Perhaps, this could be added to the list of dependencies for gcp ?

_call non-retriable exception: Disallowed unicode characters present in object name ''demo/feature/numbers/partition=npartitions=1
0      object
405       .../part...''
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gcsfs/core.py", line 507, in _call
    self.validate_response(status, contents, json, path, headers)
  File "/usr/local/lib/python3.7/dist-packages/gcsfs/core.py", line 1228, in validate_response
    raise HttpError(error)
gcsfs.utils.HttpError: Disallowed unicode characters present in object name ''demo/feature/numbers/partition=npartitions=1
0      object
405       .../part...'

**Comment by toby-coleman** [comment]
Also added a Google Cloud storage example to the [tutorial notebook](https://colab.research.google.com/github/bytehub-ai/code-examples/blob/main/tutorials/04_using_cloud_storage.ipynb).

**Comment by sharabhshukla** [comment]
yeah, that worked for me. thanks for the quick turnaround!
